#!/usr/bin/env bash
# check_phase_1.sh — Gate check for Phase 1 — Attack Taxonomy & Baselines
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 1 — Attack Taxonomy & Baselines ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/2] Baseline behavior captured for at least 1 agent... "
if python scripts/run_baselines.py --agent langchain_react --task simple_tool_call --seed 42 > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Baseline behavior captured for at least 1 agent")
    ERRORS+=("        Command: python scripts/run_baselines.py --agent langchain_react --task simple_tool_call --seed 42")
fi

echo -n "  [2/2] Attack taxonomy document exists... "
if test -f docs/attack_taxonomy.md > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Attack taxonomy document exists")
    ERRORS+=("        Command: test -f docs/attack_taxonomy.md")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 1 — Attack Taxonomy & Baselines — ALL CHECKS PASSED"
