#!/usr/bin/env bash
# check_phase_3.sh — Gate check for Phase 3 — Defense Evaluation
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 3 — Defense Evaluation ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/1] At least 1 defense runs successfully... "
if python scripts/run_defenses.py --agent langchain_react --attack prompt_injection --defense input_sanitizer --seed 42 > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: At least 1 defense runs successfully")
    ERRORS+=("        Command: python scripts/run_defenses.py --agent langchain_react --attack prompt_injection --defense input_sanitizer --seed 42")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 3 — Defense Evaluation — ALL CHECKS PASSED"
