#!/usr/bin/env bash
# sweep.sh — Orchestrate all experiments for Agent Security Red-Team Framework
# AUTO-GENERATED by gen_sweep.py from project.yaml
# Re-run generator after changing project.yaml experiment matrix.
set -euo pipefail

SEEDS="42,123,456"
PARTS="all"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
    echo "Usage: bash $0 [--parts {1,2,3,all}] [--seeds SEED_LIST]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --parts) PARTS="$2"; shift 2 ;;
        --seeds) SEEDS="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; usage ;;
    esac
done

IFS=',' read -ra SEED_ARRAY <<< "$SEEDS"
cd "$PROJECT_DIR"
export PYTHONHASHSEED=0

run_part1() {
    echo "=== Part 1: baseline_behavior ==="
    for method in langchain_react crewai_multi autogen_chat; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/run_baselines.py \
                --task simple_tool_call
        done
    done
}

run_part2() {
    echo "=== Part 2: attacks ==="
    for method in prompt_injection tool_misuse privilege_escalation memory_poisoning output_manipulation; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/run_attacks.py \
                --agent langchain_react
        done
    done
}

run_part3() {
    echo "=== Part 3: defenses ==="
    for method in input_sanitizer tool_permission_boundary memory_integrity_check output_validator; do
        for seed in "${SEED_ARRAY[@]}"; do
            echo "  $method / seed $seed"
            python scripts/run_defenses.py \
                --agent langchain_react --attack prompt_injection
        done
    done
}

case "$PARTS" in
    1) run_part1 ;;
    2) run_part2 ;;
    3) run_part3 ;;
    all) run_part1; run_part2; run_part3 ;;
    *) echo "Unknown part: $PARTS"; usage ;;
esac

echo ''
echo "=== Sweep complete ==="
